kubectl create secret generic backend-secret `
  --namespace dast `
  --from-literal=ENTRA_TENANT_ID="5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb" `
  --from-literal=ENTRA_CLIENT_ID="dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9" `
  --from-literal=ENTRA_CLIENT_SECRET="cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe" `
  --from-literal=SESSION_SECRET="bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd"