kubectl create secret generic backend-secret `
  --namespace jesa `
  --from-literal=ENTRA_TENANT_ID=5054727b-2e44-4f37-8b1b-57b988b26b5b `
  --from-literal=ENTRA_CLIENT_ID=de697752-9fc4-458f-8144-7925108aa749 `
  --from-literal=ENTRA_CLIENT_SECRET=cZb8Q~rQfC6HcHVQ35lFAzuuci3grW0c~U2oUbKe `
  --from-literal=SESSION_SECRET=b185f37e-b0d4-405f-9518-dcda98b4bc5d `
  --from-literal=BACKEND_URL=https://jesa.aymanekenbouch.online `
  --from-literal=FRONTEND_URL=https://jesa.aymanekenbouch.online `
  --from-literal=PORT=4000  