kubectl create secret generic backend-secret `
  --namespace jesa `
  --from-literal=ENTRA_TENANT_ID=5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb `
  --from-literal=ENTRA_CLIENT_ID=dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9 `
  --from-literal=ENTRA_CLIENT_SECRET=cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe `
  --from-literal=SESSION_SECRET=bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd `
  --from-literal=BACKEND_URL=https://jesa.aymanekenbouch.online `
  --from-literal=FRONTEND_URL=https://jesa.aymanekenbouch.online `
  --from-literal=PORT=4000  